# SwiftLint configuration for ReadMoreLabel project

# Target paths
included:
  - Sources
  - Tests
  - Example
excluded:
  - .build
  - .swiftpm
  - Carthage
  - Pods
  - DerivedData
  - Scripts

# Reporter
reporter: "github-actions-logging"

# Disabled rules from default enabled rules
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - explicit_acl
  - explicit_top_level_acl
  - file_header
  - trailing_comma
  - type_contents_order
  - opening_brace
  - vertical_whitespace_closing_braces
  - explicit_type_interface
  - multiline_parameters
  - redundant_objc_attribute
  - large_tuple
  - implicitly_unwrapped_optional
  - test_case_accessibility
  - line_length
  - function_parameter_count
  - closure_parameter_position
  - force_cast
  - for_where
  - unneeded_override
  - explicit_self

# Additional opt-in rules to enable
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - first_where
  - last_where
  - sorted_imports
  - switch_case_alignment

# Code style/complexity thresholds (adjusted for ReadMoreLabel project)
type_body_length:
  warning: 400  # Considering ReadMoreLabel class size
  error: 600

file_length:
  warning: 800  # Considering ReadMoreLabel.swift file size
  error: 1500

function_body_length:
  warning: 100  # Considering complex TextKit-related methods
  error: 150

cyclomatic_complexity:
  warning: 15   # Considering TextKit logic with many conditionals
  error: 35     # Considering complex methods in Example app

# Nesting depth
nesting:
  type_level: 5
  function_level: 10