# ReadMoreLabel 프로젝트용 SwiftLint 설정

# 대상 경로
included:
  - Sources
  - Tests
  - Example
excluded:
  - .build
  - .swiftpm
  - Carthage
  - Pods
  - DerivedData
  - Scripts

# 리포터
reporter: "github-actions-logging"

# 기본 활성화된 규칙 중 비활성화할 규칙들
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - explicit_acl
  - explicit_top_level_acl
  - file_header
  - trailing_comma
  - type_contents_order
  - opening_brace
  - vertical_whitespace_closing_braces
  - explicit_type_interface
  - multiline_parameters
  - redundant_objc_attribute
  - large_tuple
  - implicitly_unwrapped_optional
  - test_case_accessibility
  - line_length
  - function_parameter_count
  - closure_parameter_position
  - force_cast
  - for_where
  - unneeded_override
  - explicit_self

# 추가로 활성화할 규칙들 (opt-in)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - first_where
  - last_where
  - sorted_imports
  - switch_case_alignment

# 코드 스타일/복잡도 임계치 (ReadMoreLabel 프로젝트에 맞게 조정)
type_body_length:
  warning: 400  # ReadMoreLabel 클래스 크기 고려
  error: 600

file_length:
  warning: 800  # ReadMoreLabel.swift 파일 크기 고려
  error: 1500

function_body_length:
  warning: 100  # TextKit 관련 복잡한 메서드 고려
  error: 150

cyclomatic_complexity:
  warning: 15   # 조건문이 많은 TextKit 로직 고려
  error: 35     # Example 앱의 복잡한 메서드 고려

# 중첩 깊이
nesting:
  type_level: 5
  function_level: 10